export default {
  floatNav: {
    comments: 'Comments',
    show: 'Show',
    join: 'Join',
    top: 'Top',
    mine: 'Mine',
    order: 'Order',
    back: 'Back',
    language: 'Lang',
  },
  placeholder: {
    enter: 'enter',
    writecomment: 'Write a comments…',
    saysomething: 'Say something…',
    contactname: 'Contact name',
    mobilenumber: 'Mobile number',
    code: 'Code',
    city: 'City',
    numberfind: 'Please input the complete number',
  },
  // 通用 Common
  common: {
    all: 'All',
    livevideo: 'Live video',
    information: 'Information',
    invite: 'Invite',
    waitstatus: ' people are waiting for this live photo',
    watchstatus: ' people are watching this live photo',
    watchedstatus: ' people have watched this live photo',
    home: 'Home',
    like: 'Like',
    reward: 'Reward',
    share: 'Share',
    original: 'Original',
    print: 'Print',
    poster: 'Poster',
    longpress: 'Long press for saving',
    photographer: 'Photographer',
    retoucher: 'Retoucher',
    ok: 'OK',
    cancel: 'Cancel',
    download: 'Download',
    more: 'More',
    loading: 'loading...',
    nomore: 'No more',
    dropdown: 'Drop down ~',
    newcome: 'Click to view new photos ~',
    nophoto: 'No photos for the time being,',
    novideo: 'No videos for the time being,',
    later: 'come back later.',
    openinwx: 'Please open in wechat',
  },
  // 合集页面 list
  list: {
    hot: 'Hot',
    livephoto: 'Live photo',
  },
  // 活动信息页 info
  info: {
    client: 'photoplus Mobile client',
    download: 'Download',
    freeuse: 'Free trial-photoplus',
    go: 'Enter',
    introduction: 'Introduction',
  },
  // 预约页面 appointment
  appointment: {
    title: 'Order',
    welcome: 'Welcome to online booking shooting，<br>please enter information and submit',
    name: 'Name',
    phone: 'Phone',
    place: 'City',
    get: 'Get',
    submit: 'Submit',
    submitsucc: 'The photographer will contact you as soon as possible after successful submission~',
    // 谱时的
    pushititle: 'Making an online reservation for PLUS live photo streaming service',
    pushiyouhui: 'Submit the order on the day of the event, you will get 20% off of your first order. (The standardized service includes one photographer, one photo retoucher and the live photo streaming service.) ',
    pushicontact: 'Once receiving your orders, we shall contact you as soon as possible~<br>Or please feel free to call us by our service line:',
    pushirelate: 'Brands that you are familiar with also choose us (PLUS) ',
  },
  // 品牌
  brand: {
    photoplus: '"photoplus" is a proprietary software launched by CHENGYING(BEIJING)TECHNOLOGY CO.,LTD that enables photographer to upload imageries and videos from cameras with ease and to publish content via personalized webpage in social media. It has been called the  lucrative photography equipment. With the help of photoplus, photographer can now take care of photo shooting, digital photo uploading, photo editing, photo retouching and live photo streaming single handed. photoplus has been utilized in a vast range of scenarios such as PR event photography, sports photography, weddings photography and child photography.',
    aboutplus: 'About PLUS',
    service: 'Our Services',
    servicetype: 'Forum / Stage Performance / Sports Event / Fashion Show / Annual Gala & Celebration / Wedding / Various Conferences and Events',
    plus: 'Services cover more than 100 regions and countries worldwide; Having signed over 3000 professional photographers all over the world; Offering services for more than 5000 enterprises and brands globally; Having provided photography services for 30,000 events; Live photo streaming pages have been watched by over 100 million people globally.',
    sloganplus: 'PLUS -— One-stop Service Expert in Cloud Photography & Videography',
    ewmplus: 'To discover more exciting events, <br>scan the QR code to visit our WeChat Official Account',
  }
}
