export default {
  floatNav: {
    comments: '评论',
    show: '秀图',
    join: '互动',
    top: '顶部',
    mine: '我的',
    order: '预约',
    back: '返回',
    language: '语言',
  },
  placeholder: {
    enter: '进入',
    writecomment: '请输入评论…',
    saysomething: '分享一下此刻的心情…',
    contactname: '请输入姓名',
    mobilenumber: '请输入手机号',
    code: '请输入验证码',
    city: '请输入所在城市',
    numberfind: '请输入完整标识字母或数字',
  },
  // 通用 Common
  common: {
    all: '全部',
    livevideo: '视频直播',
    information: '活动信息',
    invite: '邀请',
    waitstatus: '人正在等待收看此次图片直播',
    watchstatus: '人正在收看此次图片直播',
    watchedstatus: '人已收看此次图片直播',
    home: '主会场',
    like: '喜欢',
    reward: '打赏',
    share: '分享',
    original: '原图',
    print: '打印',
    poster: '海报',
    longpress: '长按图片可保存',
    photographer: '摄影',
    retoucher: '修图',
    ok: '确认',
    cancel: '取消',
    download: '下载',
    more: '查看更多',
    loading: '加载中...',
    nomore: '没有更多了',
    dropdown: '下拉有惊喜~',
    newcome: '有新图进入，点击更新~',
    nophoto: '这里暂时没有图片',
    novideo: '这里暂时没有视频',
    later: '稍后再来哦~',
    openinwx: '请在微信客户端打开',
  },
  // 合集页面 list
  list: {
    hot: '热门图片',
    livephoto: '图片直播入口',
  },
  // 活动信息页 info
  info: {
    client: 'photoplus 移动客户端',
    download: '点击下载',
    freeuse: '免费试用 photoplus',
    go: '立即前往',
    introduction: '活动简介',
  },
  // 预约页面 appointment
  appointment: {
    title: '预约咨询',
    welcome: '欢迎在线预约拍摄,请输入拍摄信息并提交',
    name: '联系人',
    phone: '电话',
    place: '拍摄地',
    get: '获取验证码',
    submit: '提交预约',
    submitsucc: '提交预约后，摄影师会以最快的速度联系您~',
    // 谱时
    pushititle: '在线预约谱时图片直播',
    pushiyouhui: '活动当日提交预约，领取新人首单专属8折优惠（包含1机位摄影服务，1位修图师修图服务及图片直播服务）',
    pushicontact: '提交信息后，我们会以最快的速度联系您~<br>或拨打免费客服咨询电话：',
    pushirelate: '你身边的品牌也在选择谱时',
  },
  // 品牌
  brand: {
    photoplus: '“photoplus” 是承影互联（北京）科技有限公司推出的一款帮助摄影师完成即时影像交付和社交媒体传播的云摄影工具，是一款“能赚钱的云摄影工具”。 通过photoplus，摄影师一人即可完成拍摄上传、选图修图、交付分享等工作，photoplus目前已被广泛应用于各种活动赛事及个人写真、婚礼跟拍、儿童摄影等拍摄场景。',
    aboutplus: '关于谱时',
    service: '我们的服务',
    servicetype: '会议论坛 / 文化演出 / 体育赛事 / 时尚秀场 /<br>年会庆典 / 婚礼现场 / 各类发布会',
    plus: '服务覆盖100多个国家和地区<br>在全球范围内签约3000余名专业摄影师<br>服务全球5000多个企业和品牌<br>拍摄超3万场活动<br>图片直播页面全球传播超1亿人次',
    sloganplus: '谱时 — 活动云拍摄全案专家',
    ewmplus: '长按识别二维码<br>关注公众号观看更多精彩活动',
  }
}
